source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DIAuth_Example', :exclusive => true do
  pod "DIAuth", :path => "../"
end

target 'DIAuth_Tests', :exclusive => true do
  pod "DIAuth", :path => "../"

  
end
